# Generated by Django 6.0.4 on 2026-05-13 04:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Банк')),
                ('account_number', models.CharField(max_length=30, verbose_name='Номер счёта')),
                ('statement_date', models.DateField(verbose_name='Дата выписки')),
                ('file_original', models.FileField(upload_to='bank_statements/', verbose_name='Файл выписки')),
                ('status', models.CharField(choices=[('imported', 'Импортирована'), ('processed', 'Обработана'), ('error', 'Ошибка')], default='imported', max_length=15)),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='Всего транзакций')),
                ('matched_transactions', models.PositiveIntegerField(default=0, verbose_name='Сопоставлено')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Банковская выписка',
                'verbose_name_plural': 'Банковские выписки',
            },
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(help_text='membership, target, electricity', max_length=20, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_regular', models.BooleanField(default=True, help_text='Начисляется ежегодно', verbose_name='Регулярный')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, help_text='Базовая сумма для начисления', max_digits=10, verbose_name='Сумма по умолчанию')),
                ('unit', models.CharField(default='участок', help_text='участок, сотка, кВт·ч', max_length=20, verbose_name='Единица измерения')),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Если зависит от площади или потребления', max_digits=10, verbose_name='Тариф за единицу')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория взноса',
                'verbose_name_plural': 'Категории взносов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма начисления')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплачено')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('partial', 'Частично оплачено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=15, verbose_name='Статус')),
                ('penalty_rate', models.DecimalField(decimal_places=3, default=0, help_text='Например, 0.1% в день от суммы долга', max_digits=5, verbose_name='Ставка пени (% в день)')),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Начислено пени')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='land.landplot', verbose_name='Участок')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='users.owner', verbose_name='Владелец')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='payments.paymentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Начисление',
                'verbose_name_plural': 'Начисления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата платежа')),
                ('payment_method', models.CharField(choices=[('bank', 'Банковский перевод'), ('cash', 'Наличные'), ('terminal', 'Терминал'), ('online', 'Онлайн-платёж')], default='bank', max_length=10, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('processed', 'Проведён'), ('pending', 'В обработке'), ('rejected', 'Отклонён')], default='processed', max_length=15, verbose_name='Статус')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Банк')),
                ('bank_account', models.CharField(blank=True, max_length=30, verbose_name='Счёт плательщика')),
                ('transaction_id', models.CharField(blank=True, max_length=100, unique=True, verbose_name='ID транзакции')),
                ('payment_purpose', models.TextField(blank=True, verbose_name='Назначение платежа')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Квитанция')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.assessment', verbose_name='Начисление')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='Дата операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payer_name', models.CharField(max_length=200, verbose_name='Плательщик')),
                ('payer_account', models.CharField(blank=True, max_length=30, verbose_name='Счёт плательщика')),
                ('payer_inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН плательщика')),
                ('payment_purpose', models.TextField(verbose_name='Назначение платежа')),
                ('is_matched', models.BooleanField(default=False, verbose_name='Сопоставлено')),
                ('match_confidence', models.FloatField(default=0, verbose_name='Точность сопоставления (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='users.owner')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.bankstatement')),
                ('matched_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Банковская транзакция',
                'verbose_name_plural': 'Банковские транзакции',
            },
        ),
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('quarter', models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартал')),
                ('start_date', models.DateField(verbose_name='Начало периода')),
                ('end_date', models.DateField(verbose_name='Конец периода')),
                ('due_date', models.DateField(verbose_name='Оплатить до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Период оплаты',
                'verbose_name_plural': 'Периоды оплаты',
                'ordering': ['-year', '-quarter'],
                'unique_together': {('year', 'quarter')},
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='payments.paymentperiod', verbose_name='Период'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['owner', 'status'], name='payments_as_owner_i_864fb7_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['land_plot', 'status'], name='payments_as_land_pl_36016d_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['period', 'status'], name='payments_as_period__f3a30c_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['category', 'status'], name='payments_as_categor_1df8fc_idx'),
        ),
    ]
