# Generated by Django 6.0.4 on 2026-05-04 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(help_text='Формат: XX:XX:XXXXXXXX:XXX', max_length=30, unique=True, verbose_name='Кадастровый номер')),
                ('plot_number', models.CharField(db_index=True, max_length=10, verbose_name='Номер участка')),
                ('area_sqm', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Площадь (кв.м)')),
                ('address', models.CharField(blank=True, help_text='Описание местоположения: улица, линия и т.п.', max_length=255, verbose_name='Расположение')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('abandoned', 'Заброшенный'), ('disputed', 'Спорный')], db_index=True, default='active', max_length=10, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, help_text='Внутренние заметки, не видны владельцам', verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Земельный участок',
                'verbose_name_plural': 'Земельные участки',
                'ordering': ['plot_number'],
                'indexes': [models.Index(fields=['status'], name='land_landpl_status_02716e_idx'), models.Index(fields=['cadastral_number'], name='land_landpl_cadastr_49d0fd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='both_coordinates_set_or_none')],
            },
        ),
    ]
