"""
Django settings for SNT project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b3li&bieb5fsfh*!gozf@7a9e^&%#hxt&zwc8fxux&b*62nz6-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

AUTH_USER_MODEL = 'accounts.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'django_filters',
    
    'common',
    'accounts',
    'land',
    'users',
    'calls',
    'payments',
    'organizations',
    'subscriptions',
    'voting',
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# Время сессии
SESSION_COOKIE_AGE = 86400  # 24 часа
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.UserActivityMiddleware',
    'accounts.middleware.OrganizationMiddleware',
    # middleware для защиты API
    'common.middleware.RequestMiddleware',                    # Сохранение request в потоке
    'common.middleware.APIAccessLoggingMiddleware',          # Логирование API запросов
    'common.middleware.APIRateLimitMiddleware',              # Ограничение частоты запросов
    'common.middleware.APIIPAccessMiddleware',               # Ограничение по IP
    'common.middleware.APITimeRestrictionMiddleware',        # Ограничение по времени
    'common.middleware.TariffLimitMiddleware',               # Проверка тарифных лимитов
    'common.middleware.APIMaintenanceMiddleware',            # Режим обслуживания
    'common.middleware.APIRequestSizeMiddleware',            # Ограничение размера запроса
    'common.middleware.APISecurityHeadersMiddleware',        # Security headers
    'common.middleware.APICSRFProtectionMiddleware',         # CSRF защита
]

# API Security Settings
# Белый список IP (если пустой - проверка отключена)
ALLOWED_API_IPS = [
    '127.0.0.1',
    '85.143.101.0/24',  # Ваша офисная сеть
    # Добавьте IP ваших серверов
]

# Чёрный список IP
BLOCKED_API_IPS = [
    # '192.168.1.100',  # Пример заблокированного IP
]

# CORS настройки (если API используется с других доменов)
CORS_ALLOWED_ORIGINS = [
    'https://snt.ru',
    'https://api.snt.ru',
    'http://localhost:3000',
    'http://127.0.0.1:8000',
]

# Режим обслуживания (можно включать через админку)
API_MAINTENANCE_MODE = False

# CSRF настройки для API
CSRF_TRUSTED_ORIGINS = [
    'snt-crm.ru',
    'test.snt-crm.ru',
    'api.snt-crm.ru',
    'localhost',
    '127.0.0.1',
]

# API Rate Limits (можно переопределить в middleware)
API_RATE_LIMITS = {
    'default': 60,
    'auth': 10,
    'create': 30,
    'export': 5,
    'import': 3,
    'payment': 20,
}

ROOT_URLCONF = 'SNT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'common.context_processors.user_organization',
            ],
        },
    },
]

WSGI_APPLICATION = 'SNT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'snt_crm'),
        'USER': os.getenv('DB_USER', 'snt_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'snt_secure_password_2024'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'CONN_MAX_AGE': 600,
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Asterisk AMI/ARI
ASTERISK_AMI_HOST = os.environ.get('ASTERISK_AMI_HOST', '127.0.0.1')
ASTERISK_AMI_PORT = int(os.environ.get('ASTERISK_AMI_PORT', 5038))
ASTERISK_AMI_USER = os.environ.get('ASTERISK_AMI_USER', 'crm_user')
ASTERISK_AMI_SECRET = os.environ.get('ASTERISK_AMI_SECRET', '')
ASTERISK_RECORDING_PATH = os.environ.get(
    'ASTERISK_RECORDING_PATH',
    '/var/spool/asterisk/monitor/',
)

# Реквизиты СНТ
SNT_NAME = 'СНТ "Строитель-43"'
SNT_INN = '2462039398'
SNT_KPP = '123001001'
SNT_ACCOUNT = '40703810500600004095'
SNT_BANK_NAME = 'ВТБ'
SNT_BANK_BIK = '044525411'
SNT_BANK_CORR = '30101810145250000411'
SNT_CHAIRMAN = 'Председатель правления'

# CSRF настройки
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = True
CSRF_USE_SESSIONS = False
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Создаем директорию для логов
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

# Настройка ротации логов
# Максимальный размер файла лога (в байтах) - 50 МБ
LOG_MAX_BYTES = 50 * 1024 * 1024
# Количество сохраняемых файлов лога
LOG_BACKUP_COUNT = 10
# Количество сохраняемых файлов для ошибок (больше, т.к. важнее)
ERROR_BACKUP_COUNT = 20

# Настройка логирования с ротацией
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} [{name}:{lineno}] {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} [{name}] {message}',
            'style': '{',
        },
        'payment_detailed': {
            'format': '[{asctime}] {levelname} [{name}:{lineno}] {funcName} - {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        # Исправленный JSON форматтер - используем обычный string format
        'json': {
            'format': '%(asctime)s - %(levelname)s - %(name)s - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # Консольный вывод
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['require_debug_true'],
        },
        'console_payments': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'payment_detailed',
            'filters': ['require_debug_true'],
        },
        
        # Основные файловые логгеры с ротацией
        'file_accounts': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'accounts.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        'file_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'errors.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': ERROR_BACKUP_COUNT,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'file_security': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'security.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        'file_debug': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'debug.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        'file_django': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        
        # Payments модуль
        'file_payments': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'payments.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'payment_detailed',
            'encoding': 'utf-8',
        },
        'file_payments_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'payments_errors.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': ERROR_BACKUP_COUNT,
            'formatter': 'payment_detailed',
            'encoding': 'utf-8',
        },
        'file_bank_parser': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'bank_parser.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'payment_detailed',
            'encoding': 'utf-8',
        },
        'file_email_service': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'email_service.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'payment_detailed',
            'encoding': 'utf-8',
        },
        'file_qr_generator': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'qr_generator.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'payment_detailed',
            'encoding': 'utf-8',
        },
        
        # Land модуль
        'file_land': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'land.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        'file_land_errors': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'land_errors.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        
        # Organizations модуль
        'file_organizations': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'organizations.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        
        # Subscriptions модуль
        'file_subscriptions': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'subscriptions.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        
        # Users модуль
        'file_users': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'users.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        
        # Voting модуль
        'file_voting': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'voting.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        
        # API логи (отключен JSON формат до исправления)
        'file_api': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'api.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
        
        # Производительность
        'file_performance': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'performance.log'),
            'maxBytes': LOG_MAX_BYTES,
            'backupCount': LOG_BACKUP_COUNT,
            'formatter': 'detailed',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        # Корневой логгер
        '': {
            'handlers': ['console', 'file_errors'],
            'level': 'INFO',
        },
        
        # Django логгеры
        'django': {
            'handlers': ['console', 'file_django', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file_errors', 'file_api', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file_django'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'file_errors', 'file_performance'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['file_security', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        
        # Accounts модуль
        'accounts': {
            'handlers': ['file_accounts', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounts.views': {
            'handlers': ['file_accounts', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounts.signals': {
            'handlers': ['file_accounts', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounts.middleware': {
            'handlers': ['file_accounts', 'console', 'file_performance'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounts.serializers': {
            'handlers': ['file_accounts', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # Payments модуль
        'payments': {
            'handlers': ['file_payments', 'console_payments', 'file_payments_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'payments.views': {
            'handlers': ['file_payments', 'console_payments', 'file_payments_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'payments.models': {
            'handlers': ['file_payments', 'file_payments_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'payments.serializers': {
            'handlers': ['file_payments'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'payments.signals': {
            'handlers': ['file_payments'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'payments.bank_parser': {
            'handlers': ['file_bank_parser', 'console_payments', 'file_payments_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'payments.email_service': {
            'handlers': ['file_email_service', 'console_payments', 'file_payments_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'payments.qr_generator': {
            'handlers': ['file_qr_generator', 'console_payments'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # Land модуль
        'land': {
            'handlers': ['file_land', 'console', 'file_land_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'land.views': {
            'handlers': ['file_land', 'console', 'file_land_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'land.services': {
            'handlers': ['file_land', 'console', 'file_land_errors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # Organizations модуль
        'organizations': {
            'handlers': ['file_organizations', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'organizations.views': {
            'handlers': ['file_organizations', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # Subscriptions модуль
        'subscriptions': {
            'handlers': ['file_subscriptions', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'subscriptions.views': {
            'handlers': ['file_subscriptions', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'subscriptions.payment_service': {
            'handlers': ['file_subscriptions', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'subscriptions.signals': {
            'handlers': ['file_subscriptions', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # Users модуль
        'users': {
            'handlers': ['file_users', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users.views': {
            'handlers': ['file_users', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users.signals': {
            'handlers': ['file_users', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'users.serializers': {
            'handlers': ['file_users', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # Voting модуль
        'voting': {
            'handlers': ['file_voting', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'voting.views': {
            'handlers': ['file_voting', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'voting.signals': {
            'handlers': ['file_voting', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'voting.serializers': {
            'handlers': ['file_voting', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'voting.permissions': {
            'handlers': ['file_voting', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        
        # API логгер
        'api': {
            'handlers': ['file_api', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Дополнительные настройки для payments
PAYMENTS_CONFIG = {
    'QR_VERSION': 3,
    'QR_BOX_SIZE': 8,
    'QR_BORDER': 2,
    'QR_ERROR_CORRECTION': 'M',
    'MAX_ASSESSMENTS_PER_PAGE': 50,
    'BULK_EMAIL_BATCH_SIZE': 100,
    'BANK_STATEMENT_RETENTION_DAYS': 365,
    'PAYMENT_RETENTION_DAYS': 730,
    'ENABLE_PDF_GENERATION': True,
    'ENABLE_QR_CODE': True,
    'DEFAULT_PENALTY_RATE': 0.1,
}

ROSREESTR_API_KEY = '53ba1b7a55abbа14aa97eff3a5220792'
ROSREESTR_API_URL = 'https://api-cloud.ru/api/rosreestr.php'
ROSREESTR_TIMEOUT = 120

KADNET_API_KEY = ''

# Email настройки
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'akuliniwan@yandex.ru'
EMAIL_HOST_PASSWORD = 'password'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Email настройки для массовых рассылок
EMAIL_BULK_BATCH_SIZE = 50
EMAIL_RETRY_ATTEMPTS = 3
EMAIL_RETRY_DELAY = 5

# Для разработки (чтобы не отправлять реальные письма)
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Настройки кеширования
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

PAYMENTS_CACHE_TIMEOUT = 300