# Generated by Django 6.0.4 on 2026-05-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Владелец',
                'verbose_name_plural': 'Владельцы',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.CharField(default='1/1', help_text='Например: 1/1, 1/2, 1/3 и т.д.', max_length=20, verbose_name='Доля')),
                ('ownership_since', models.DateField(blank=True, null=True, verbose_name='Дата вступления во владение')),
                ('document_basis', models.CharField(blank=True, help_text='Номер свидетельства или выписки из ЕГРН', max_length=255, verbose_name='Документ-основание')),
                ('land_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='land.landplot')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='users.owner')),
            ],
            options={
                'verbose_name': 'Право собственности',
                'verbose_name_plural': 'Права собственности',
                'unique_together': {('owner', 'land_plot')},
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='land_plots',
            field=models.ManyToManyField(related_name='owners', through='users.Ownership', to='land.landplot'),
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ph', 'Телефон'), ('em', 'Email')], max_length=2, verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Актуальный')),
                ('is_verified', models.BooleanField(default=False, help_text='Подтверждено ли, что контакт принадлежит владельцу', verbose_name='Подтверждён')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.owner')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
                'ordering': ['-is_active', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'type', 'is_active'], name='users_conta_owner_i_10bfac_idx')],
            },
        ),
    ]
