# Generated by Django 6.0.4 on 2026-05-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('land', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(db_index=True, max_length=20, verbose_name='Номер звонящего')),
                ('called_number', models.CharField(blank=True, help_text='Внутренний номер СНТ, на который поступил звонок', max_length=20, verbose_name='Номер назначения')),
                ('direction', models.CharField(choices=[('in', 'Входящий'), ('out', 'Исходящий'), ('missed', 'Пропущенный')], default='in', max_length=10, verbose_name='Направление')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processed', 'Обработан'), ('archived', 'Архивирован')], db_index=True, default='new', max_length=15, verbose_name='Статус обработки')),
                ('started_at', models.DateTimeField(db_index=True, verbose_name='Начало звонка')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание звонка')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='call_recordings/%Y/%m/', verbose_name='Файл записи')),
                ('asterisk_uniqueid', models.CharField(blank=True, help_text='Уникальный идентификатор канала в Asterisk', max_length=50, null=True, unique=True, verbose_name='Asterisk UniqueID')),
                ('asterisk_channel', models.CharField(blank=True, help_text='Название канала Asterisk (SIP/dialer/...)', max_length=100, verbose_name='Канал')),
                ('asterisk_recording_file', models.CharField(blank=True, help_text='Полный путь к wav-файлу на сервере Asterisk', max_length=500, verbose_name='Путь к файлу в Asterisk')),
                ('operator_note', models.TextField(blank=True, help_text='Краткое описание сути разговора', verbose_name='Заметка оператора')),
                ('tags', models.CharField(blank=True, help_text='Теги через запятую: жалоба, должник, электричество', max_length=200, verbose_name='Теги')),
                ('is_important', models.BooleanField(default=False, help_text='Пометить как важный звонок', verbose_name='Важный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('land_plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='land.landplot', verbose_name='Участок')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='users.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Запись звонка',
                'verbose_name_plural': 'Записи звонков',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['owner', 'started_at'], name='calls_callr_owner_i_719c26_idx'), models.Index(fields=['caller_number', 'started_at'], name='calls_callr_caller__2dd176_idx'), models.Index(fields=['status', 'started_at'], name='calls_callr_status_28e3f3_idx'), models.Index(fields=['asterisk_uniqueid'], name='calls_callr_asteris_c3bc4d_idx')],
            },
        ),
    ]
